import Head from 'next/head'
import { Roboto } from 'next/font/google'
import { Header } from '@/components/Header'
import HomePage from './home'

export const robotoRegular = Roboto({
  weight: '400',
  subsets: ['latin'],
  style: 'normal',
})

export const robotoBold = Roboto({
  weight: '700',
  subsets: ['latin'],
  style: 'normal',
})

export default function Home() {
  return (
    <>
      <Head>
        <title>App Rick and Martin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <>
        <HomePage />
      </>
    </>
  )
}
